# Swagger API documentation placeholder
openapi: 3.0.3
info:
  title: Dashboard API
  version: 1.0.0
paths:
  /api/auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email: { type: string }
                password: { type: string }
                firstName: { type: string }
                lastName: { type: string }
      responses:
        '201':
          description: User created
  /api/dashboard/stats:
    get:
      summary: Get dashboard statistics
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Dashboard stats
  /api/activities:
    get:
      summary: Get recent activities
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of recent activities
    post:
      summary: Create a new activity
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type: { type: string, enum: ['LEAD_QUALIFIED', 'CAMPAIGN_MILESTONE', 'AI_OPTIMIZATION', 'LEAD_SCORED'] }
                action: { type: string }
                details: { type: string }
                leadId: { type: string, format: uuid, nullable: true }
                campaignId: { type: string, format: uuid, nullable: true }
      responses:
        '201':
          description: Activity created
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT